import type {Metadata} from "next";

import {Inter as FontSans} from "next/font/google";

import "./globals.css";
import {ThemeProvider} from "@/providers/theme-provider";
import {cn} from "@/lib/utils";
import QueryProviders from "@/providers/query-provider";
import Navbar from "@/components/navbar";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Layout = ({children}: Readonly<{children: React.ReactNode}>) => {
  return (
    <ThemeProvider disableTransitionOnChange enableSystem attribute="class" defaultTheme="system">
      <QueryProviders>
        <Navbar />
        <div className={cn("bg-background font-sans antialiased", fontSans.variable)}>
          {children}
        </div>
      </QueryProviders>
    </ThemeProvider>
  );
};

export default Layout;
